apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-svc
  labels:
    app.kubernetes.io/name: {{ .Values.app_name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range $port := .Values.service.ports }}
    - port: {{ $port.containerPort }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ .Values.app_name }}
    app.kubernetes.io/instance: {{ .Release.Name }}