name: CI/CD Pipeline for web

on:
  push:
    branches:
      - dev
      - staging
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "ap-southeast-1"
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      IMAGE_URL: ${{ secrets.ECR_REGISTRY }}
      IMAGE_TAG: "${{ github.ref_name }}/_web_${{ github.sha }}"

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to AWS ECR
        run: |
          aws --version
          aws ecr get-login-password --region ${{ env.AWS_REGION }} | docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }}

      - name: Build and push Docker image
        run: |
          echo "Building Docker image: ${{ env.IMAGE_URL }}:${{ env.IMAGE_TAG }}"
          docker build -t ${{ env.IMAGE_URL }}:${{ env.IMAGE_TAG }} .
          docker push ${{ env.IMAGE_URL }}:${{ env.IMAGE_TAG }}
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
          IMAGE_URL: ${{ env.IMAGE_URL }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Run Unit Tests
        run: npm test
